apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  labels:
    realm: mss
  name: mss
  namespace: keycloak
spec:
  instanceSelector:
    matchLabels:
      app: mss-keycloak
  realm:
    displayName: MSS
    editUsernameAllowed: false
    enabled: true
    identityProviders:
    - alias: cilogon
      config:
        allowedClockSkew: "5"
        authorizationUrl: "https://cilogon.org/authorize?idphint=\
          https%3A%2F%2Ffed.huit.harvard.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Fshib.bu.edu%2Fidp%2Fshibboleth,\
          urn%3Amace%3Aincommon%3Amit.edu,\
          https%3A%2F%2Fwebauth.umass.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Fvm-shibboleth.umb.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Fidp.umassd.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Fshibboleth.umassmed.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Fneuidmsso.neu.edu%2Fidp%2Fshibboleth,\
          https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fv2.0%2Fauthorize,\
          https%3A%2F%2Fsso.uri.edu%2Fidp"
        clientAuthMethod: client_secret_post
        clientId: "cilogon:/client_id/ab05912d88d9f9cc5ea155accf420f3"
        clientSecret: ${vault.cilogon_client_secret}  # pragma: allowlist secret
        defaultScope: openid email profile org.cilogon.userinfo
        syncMode: IMPORT
        tokenUrl: https://cilogon.org/oauth2/token
        useJwksUrl: "true"
      displayName: cilogon
      enabled: true
      firstBrokerLoginFlowAlias: browser
      providerId: oidc
      trustEmail: true
    realm: mss
    registrationAllowed: false
    rememberMe: false
    resetPasswordAllowed: false
    sslRequired: external
    userManagedAccessAllowed: false
    verifyEmail: false
